package main

import (
	"net/http"
	"strings"
)

func (a *app) routes() *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /healthz", a.health)
	mux.HandleFunc("POST /api/v1/auth/login", a.limited(a.login))
	mux.HandleFunc("POST /login", a.limited(a.loginForm))
	mux.HandleFunc("POST /api/v1/auth/register", a.limited(a.register))
	mux.HandleFunc("POST /api/v1/auth/logout", a.logout)
	mux.HandleFunc("POST /api/v1/auth/change-password", a.limited(a.auth(a.changePassword)))
	mux.HandleFunc("GET /api/v1/password-policy", a.passwordPolicy)
	mux.HandleFunc("GET /api/v1/events", a.auth(a.events))
	mux.HandleFunc("POST /api/v1/message-receipts", a.auth(a.receipts))
	mux.HandleFunc("GET /api/v1/pending-deliveries", a.auth(a.pendingDeliveries))
	mux.HandleFunc("POST /api/v1/message-statuses", a.auth(a.receiptStatuses))
	mux.HandleFunc("POST /api/v1/invitations/accept", a.limited(a.acceptInvitation))
	mux.HandleFunc("POST /api/v1/invitations/join-by-code", a.limited(a.auth(a.joinInvitationByCode)))
	mux.HandleFunc("POST /api/v1/attachments", a.limited(a.auth(a.uploadAttachment)))
	mux.HandleFunc("POST /api/v1/mobile/shares/{requestID}", a.limited(a.auth(a.mobileShare)))
	mux.HandleFunc("POST /api/v1/invitations/{token}/join", a.auth(a.joinInvitation))
	mux.HandleFunc("GET /api/v1/attachments/{id}", a.auth(a.downloadAttachment))
	mux.HandleFunc("GET /api/v1/auth/me", a.auth(a.me))
	mux.HandleFunc("PUT /api/v1/user/profile", a.auth(a.updateProfile))
	mux.HandleFunc("GET /api/v1/mobile/push/config", a.auth(a.mobilePushConfig))
	mux.HandleFunc("POST /api/v1/mobile/push/devices", a.limited(a.auth(a.saveMobileDevice)))
	mux.HandleFunc("DELETE /api/v1/mobile/push/devices/{installationID}", a.auth(a.deleteMobileDevice))
	mux.HandleFunc("GET /api/v1/user/preferences", a.auth(a.userPreferences))
	mux.HandleFunc("PUT /api/v1/user/preferences", a.auth(a.updateUserPreferences))
	mux.HandleFunc("GET /api/v1/push/public-key", a.auth(a.pushPublicKey))
	mux.HandleFunc("POST /api/v1/push/subscriptions", a.auth(a.savePushSubscription))
	mux.HandleFunc("DELETE /api/v1/push/subscriptions", a.auth(a.deletePushSubscription))
	mux.HandleFunc("GET /api/v1/users", a.auth(a.users))
	mux.HandleFunc("POST /api/v1/users/{userID}/lifecycle", a.limited(a.auth(a.changeUserLifecycle)))
	mux.HandleFunc("GET /api/v1/application/settings", a.auth(a.applicationSettings))
	mux.HandleFunc("PUT /api/v1/application/settings", a.auth(a.updateApplicationSettings))
	mux.HandleFunc("GET /api/v1/families", a.auth(a.families))
	mux.HandleFunc("POST /api/v1/families", a.auth(a.createFamily))
	mux.HandleFunc("GET /api/v1/families/{familyID}/shopping", a.auth(a.shoppingItems))
	mux.HandleFunc("GET /api/v1/families/{familyID}/needs", a.auth(a.needs))
	mux.HandleFunc("POST /api/v1/families/{familyID}/needs", a.auth(a.needs))
	mux.HandleFunc("GET /api/v1/families/{familyID}/needs/{itemID}", a.auth(a.needs))
	mux.HandleFunc("PATCH /api/v1/families/{familyID}/needs/{itemID}", a.auth(a.needs))
	mux.HandleFunc("POST /api/v1/families/{familyID}/needs/{itemID}/comments", a.limited(a.auth(a.needs)))
	mux.HandleFunc("POST /api/v1/families/{familyID}/shopping", a.auth(a.addShoppingItem))
	mux.HandleFunc("PATCH /api/v1/families/{familyID}/shopping/{itemID}", a.auth(a.toggleShoppingItem))
	mux.HandleFunc("DELETE /api/v1/families/{familyID}/shopping/{itemID}", a.auth(a.deleteShoppingItem))
	mux.HandleFunc("POST /api/v1/auth/avatar", a.limited(a.auth(a.uploadAvatar)))
	mux.HandleFunc("PATCH /api/v1/families/{familyID}/members/{userID}", a.auth(a.updateFamilyMember))
	mux.HandleFunc("GET /api/v1/users/{userID}/avatar", a.auth(a.avatar))
	mux.HandleFunc("GET /api/v1/contacts", a.auth(a.contacts))
	mux.HandleFunc("POST /api/v1/users", a.auth(a.createUser))
	mux.HandleFunc("PATCH /api/v1/users/{userID}/permissions", a.auth(a.updateUserPermissions))
	mux.HandleFunc("POST /api/v1/invitations", a.auth(a.createInvitation))
	mux.HandleFunc("POST /api/v1/users/{userID}/direct-conversation", a.auth(a.directConversation))
	mux.HandleFunc("GET /api/v1/conversations", a.auth(a.conversations))
	mux.HandleFunc("GET /api/v1/favorites", a.auth(a.favorites))
	mux.HandleFunc("PUT /api/v1/conversations/{id}/favorite", a.auth(a.setFavorite))
	mux.HandleFunc("POST /api/v1/conversations", a.auth(a.createGroup))
	mux.HandleFunc("PATCH /api/v1/conversations/{id}", a.auth(a.renameConversation))
	mux.HandleFunc("POST /api/v1/conversations/{id}/members", a.auth(a.addMember))
	mux.HandleFunc("DELETE /api/v1/conversations/{id}", a.auth(a.deleteGroup))
	mux.HandleFunc("GET /api/v1/conversations/{id}/members", a.auth(a.members))
	mux.HandleFunc("DELETE /api/v1/conversations/{id}/members/{userID}", a.auth(a.removeMember))
	mux.HandleFunc("GET /api/v1/conversations/{id}/member-candidates", a.auth(a.memberCandidates))
	mux.HandleFunc("GET /api/v1/conversations/{id}/messages", a.auth(a.messages))
	mux.HandleFunc("GET /api/v1/conversations/{id}/search", a.auth(a.searchMessages))
	mux.HandleFunc("POST /api/v1/conversations/{id}/messages", a.auth(a.createMessage))
	mux.HandleFunc("POST /api/v1/conversations/{id}/delivery", a.auth(a.markDelivered))
	mux.HandleFunc("PATCH /api/v1/messages/{id}", a.auth(a.editMessage))
	mux.HandleFunc("DELETE /api/v1/messages/{id}", a.auth(a.deleteMessage))
	mux.HandleFunc("POST /api/v1/messages/{id}/reactions", a.auth(a.toggleReaction))
	mux.HandleFunc("GET /api/v1/messages/{id}/reactions", a.auth(a.messageReactions))
	static := http.FileServer(http.Dir("web"))
	mux.Handle("GET /", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.HasSuffix(r.URL.Path, ".js") || strings.HasSuffix(r.URL.Path, ".css") || strings.HasSuffix(r.URL.Path, ".html") || r.URL.Path == "/" {
			w.Header().Set("Cache-Control", "no-store")
		}
		static.ServeHTTP(w, r)
	}))
	return mux
}
