const api='/api/v1'; let conversations=[],active=null,loadVersion=0,currentUser=null;
const $=s=>document.querySelector(s);
async function request(path,options={}){const r=await fetch(api+path,{credentials:'include',headers:{'Content-Type':'application/json'},...options});if(!r.ok){const e=await r.json().catch(()=>({}));throw Error(e.error||'Ошибка запроса')}return r.status===204?null:r.json()}
function safe(v){const e=document.createElement('span');e.textContent=v;return e.innerHTML}
async function loadConversations(){conversations=await request('/conversations');$('#conversations').innerHTML=conversations.map(c=>`<button class="conversation ${c.id===active?'selected':''}" data-id="${c.id}">${safe(c.title||'Личный диалог')}</button>`).join('');$('#conversations').onclick=e=>e.target.dataset.id&&openConversation(e.target.dataset.id);if(!active&&conversations[0])openConversation(conversations[0].id)}
async function openConversation(id){const version=++loadVersion;active=id;const c=conversations.find(x=>x.id===id);$('#chatTitle').textContent=c?.title||'Диалог';$('#manageMembers').hidden=c?.kind!=='group';$('#messages').innerHTML='<p class="muted">Загрузка сообщений…</p>';try{const list=await request(`/conversations/${id}/messages`);if(version!==loadVersion||id!==active)return;$('#messages').innerHTML=list.map(m=>`<article class="message"><strong>${safe(m.authorName)}</strong><p>${m.deletedAt?'Сообщение удалено':safe(m.body)}</p><small>${new Date(m.createdAt).toLocaleString('ru-RU')}${m.editedAt?' · изменено':''}</small></article>`).join('');$('#messages').scrollTop=$('#messages').scrollHeight}catch(e){if(version===loadVersion)$('#messages').innerHTML=`<p class="error">${safe(e.message)}</p>`}}
async function login(){try{await request('/auth/login',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});await startApp()}catch(e){$('#error').textContent=e.message}}
async function startApp(){currentUser=await request('/auth/me');$('#login').hidden=true;$('#app').hidden=false;if(currentUser.Permissions?.manage_users){$('#administration').hidden=false}await loadConversations()}
$('#loginButton').onclick=login;$('#password').onkeydown=e=>{if(e.key==='Enter')login()};$('#logout').onclick=async()=>{await request('/auth/logout',{method:'POST'});location.reload()};$('#composer').onsubmit=async e=>{e.preventDefault();const body=$('#body').value.trim();if(!active||!body)return;await request(`/conversations/${active}/messages`,{method:'POST',body:JSON.stringify({body})});$('#body').value='';openConversation(active)};$('#newGroup').onclick=()=>$('#groupDialog').showModal();$('#createGroup').onclick=async e=>{e.preventDefault();const title=$('#groupTitle').value.trim();if(!title)return;await request('/conversations',{method:'POST',body:JSON.stringify({title,memberIds:[]})});$('#groupDialog').close();$('#groupTitle').value='';active=null;loadConversations()};
async function openAdmin(){try{const users=await request('/users');$('#users').innerHTML=users.map(u=>`<li><strong>${safe(u.Name)}</strong><small>${safe(u.Email)}</small></li>`).join('');$('#inviteToken').hidden=true;$('#adminDialog').showModal()}catch(e){alert(e.message)}}
$('#administration').onclick=openAdmin;$('#createInvite').onclick=async e=>{e.preventDefault();const permissions=[...document.querySelectorAll('[name=permission]:checked')].map(x=>x.value);try{const invite=await request('/invitations',{method:'POST',body:JSON.stringify({email:$('#inviteEmail').value,permissions})});$('#inviteToken').textContent=`Одноразовый код: ${invite.token}`;$('#inviteToken').hidden=false;$('#inviteEmail').value=''}catch(e){$('#inviteError').textContent=e.message}};
async function openMembers(){if(!active)return;try{const [members,candidates]=await Promise.all([request(`/conversations/${active}/members`),request(`/conversations/${active}/member-candidates`)]);const ids=new Set(members.map(u=>u.ID));$('#groupMembers').innerHTML=members.map(u=>`<li><strong>${safe(u.Name)}</strong><small>${safe(u.Email)}</small>${u.ID===currentUser.ID?'':`<button class="removeMember secondary" data-id="${safe(u.ID)}">Удалить</button>`}</li>`).join('');const options=candidates.filter(u=>!ids.has(u.ID)).map(u=>`<option value="${safe(u.ID)}">${safe(u.Name)} — ${safe(u.Email)}</option>`).join('');$('#memberSelect').innerHTML=options||'<option value="">Нет доступных пользователей</option>';$('#addMember').disabled=!options;$('#groupMembers').onclick=async e=>{if(!e.target.dataset.id)return;if(!confirm('Удалить участника из группы?'))return;await request(`/conversations/${active}/members/${encodeURIComponent(e.target.dataset.id)}`,{method:'DELETE'});openMembers();loadConversations()};$('#membersDialog').showModal()}catch(e){alert(e.message)}}
$('#manageMembers').onclick=openMembers;$('#addMember').onclick=async e=>{e.preventDefault();const userId=$('#memberSelect').value;if(!userId)return;try{await request(`/conversations/${active}/members`,{method:'POST',body:JSON.stringify({userId})});openMembers();loadConversations()}catch(e){$('#memberError').textContent=e.message}};
function connectEvents(){const scheme=location.protocol==='https:'?'wss':'ws';const socket=new WebSocket(`${scheme}://${location.host}/api/v1/events`);socket.onmessage=()=>{if(active)openConversation(active).catch(()=>{});loadConversations().catch(()=>{})};socket.onclose=()=>setTimeout(connectEvents,2000)}
request('/auth/me').then(async()=>{await startApp();connectEvents()}).catch(()=>{});
