import {safe as safeText} from './api.js';
const safe=value=>safeText(value).replaceAll('"','&quot;').replaceAll("'",'&#39;');
export const groupIcons=['','💬','🏠','👪','❤️','⭐','🎉','🎓','⚽','🎮','🛒','✈️','💼','🌿','🐾','🎵'];
export function classifyGroups(conversations,familyID){const groups=conversations.filter(c=>c.kind==='group');return {family:groups.filter(c=>familyID&&c.familyIds?.includes(familyID)),other:groups.filter(c=>!familyID||!c.familyIds?.includes(familyID))};}
export const managesGroup=c=>['owner','admin'].includes(c?.groupRole);
export function initGroups({request,locale,refresh,announce,confirm}){
 const t=(ru,en)=>locale()==='en'?en:ru;
 const iconOptions=value=>groupIcons.map(icon=>`<option value="${safe(icon)}" ${icon===value?'selected':''}>${icon||t('По умолчанию','Default')}</option>`).join('');
 function dialog(title){const d=document.createElement('dialog');d.className='groupSettingsDialog';d.setAttribute('data-no-i18n','');d.innerHTML=`<header><h2>${safe(title)}</h2><button type="button" data-close>${t('Закрыть','Close')}</button></header><div data-content></div><p class="error" role="alert"></p>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.onclick=e=>{if(e.target===d)d.close();};d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return d;}
 async function open(conversation){
  const cid=conversation.id,d=dialog(t('Группа','Group'));let busy=false;
  const content=d.querySelector('[data-content]'),error=d.querySelector('.error');
  async function perform(action,body){if(busy)return false;busy=true;error.textContent='';try{await request(`/groups/${encodeURIComponent(cid)}/${action}`,{method:'POST',body:JSON.stringify(body)});await refresh();return true;}catch(e){error.textContent=e.message;return false;}finally{busy=false;}}
  async function render(){
   try{
    const chats=await request('/conversations');conversation=chats.find(c=>c.id===cid);if(!conversation){d.close();return;}
    const members=(await request(`/conversations/${encodeURIComponent(cid)}/members`)).map(m=>({...m,Disabled:m.disabled}));if(!d.isConnected)return;
    const owner=conversation.groupRole==='owner',manager=managesGroup(conversation);
    content.innerHTML=`${conversation.ownerUnavailable?`<p class="error">${t('Владелец недоступен. Обратитесь к администратору приложения.','Owner unavailable. Contact the application administrator.')}</p>`:''}${manager?`<form data-settings><label>${t('Название','Title')}<input name="title" required maxlength="120" value="${safe(conversation.title)}"></label><label>${t('Пиктограмма','Icon')}<select name="icon">${iconOptions(conversation.icon||'')}</select></label><button>${t('Сохранить','Save')}</button></form>`:`<h3>${safe(conversation.title)}</h3>`}<h3>${t('Участники','Members')}</h3><ul class="groupMemberList">${members.map(m=>`<li><span>${safe(m.Name)} <small>${t(({owner:'Владелец',admin:'Администратор',member:'Участник'})[m.groupRole],({owner:'Owner',admin:'Administrator',member:'Member'})[m.groupRole])}${m.Disabled?' · '+t('Отключён','Disabled'):''}</small></span>${m.groupRole!=='owner'&&(owner||manager&&m.groupRole==='member')?`<button type="button" data-edit="${safe(m.ID)}">${t('Настроить','Settings')}</button>`:''}</li>`).join('')}</ul>${conversation.canInvite?`<form data-invite><h3>${t('Добавить в группу','Add to group')}</h3><label>${t('Поиск пользователя','Find user')}<input type="search" data-search autocomplete="off"></label><select name="userId" aria-label="${t('Пользователь','User')}"></select><p class="muted">${t('Добавленный участник увидит всю историю группы.','New members can read the entire group history.')}</p><button disabled>${t('Добавить','Add')}</button></form>`:''}${!owner?`<button type="button" class="dangerText" data-leave>${t('Выйти из группы','Leave group')}</button>`:`<p class="muted">${t('Чтобы выйти, сначала передайте владение другому участнику.','Transfer ownership to another member before leaving.')}</p>`}`;
    content.querySelector('[data-settings]')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;if(await perform('settings',{title:f.elements.title.value,icon:f.elements.icon.value}))announce(t('Настройки сохранены','Settings saved'));});
    content.querySelector('[data-leave]')?.addEventListener('click',async()=>{if(await confirm({title:t('Выйти из группы?','Leave group?'),message:t('Доступ к истории и вложениям будет закрыт.','Access to history and attachments will be revoked.'),confirmLabel:t('Выйти','Leave')}))if(await perform('leave',{}))d.close();});
    content.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>edit(members.find(m=>m.ID===button.dataset.edit),owner,perform,render));
    const inviteForm=content.querySelector('[data-invite]');if(inviteForm){
     const candidates=await request(`/conversations/${encodeURIComponent(cid)}/member-candidates`);if(!inviteForm.isConnected)return;
     const search=inviteForm.querySelector('[data-search]'),select=inviteForm.elements.userId,add=inviteForm.querySelector('button');
     const filter=()=>{const term=search.value.trim().toLocaleLowerCase();select.innerHTML=candidates.filter(c=>c.Name.toLocaleLowerCase().includes(term)).slice(0,100).map(c=>`<option value="${safe(c.ID)}">${safe(c.Name)}</option>`).join('');add.disabled=!select.value;};search.oninput=filter;filter();
     inviteForm.onsubmit=async e=>{e.preventDefault();if(select.value&&await perform('add',{userId:select.value}))await render();};
    }
   }catch(e){error.textContent=e.message;}
  }
  function edit(member,owner,perform,render){
   const ed=dialog(t('Участник группы','Group member'));const host=ed.querySelector('[data-content]');
   host.innerHTML=`<h3>${safe(member.Name)}</h3><form><label>${t('Роль','Role')}<select name="role" ${owner?'':'disabled'}><option value="member">${t('Участник','Member')}</option><option value="admin">${t('Администратор','Administrator')}</option></select></label><label class="groupInviteToggle"><input name="invite" type="checkbox">${t('Может приглашать участников','Can invite members')}</label><p class="muted">${t('Владелец и администраторы могут приглашать всегда. Эта настройка даёт право обычному участнику.','Owners and administrators can always invite. This setting grants that right to a regular member.')}</p><button>${t('Сохранить','Save')}</button></form><div class="actions">${owner&&!member.Disabled?`<button type="button" data-transfer>${t('Передать владение','Transfer ownership')}</button>`:''}<button type="button" class="dangerText" data-remove>${t('Удалить из группы','Remove from group')}</button></div>`;
   const f=host.querySelector('form');f.elements.role.value=member.groupRole;f.elements.invite.checked=member.canInvite;
   let editing=false;async function run(action,body){if(editing)return;editing=true;try{if(await perform(action,body)){ed.close();await render();}else ed.querySelector('.error').textContent=error.textContent;}finally{editing=false}}
   f.onsubmit=e=>{e.preventDefault();void run('permissions',{userId:member.ID,role:f.elements.role.value,canInvite:f.elements.invite.checked});};
   host.querySelector('[data-remove]').onclick=async()=>{if(await confirm({title:t('Удалить участника?','Remove member?'),message:member.Name,confirmLabel:t('Удалить','Remove'),destructive:true}))await run('remove',{userId:member.ID});};
   host.querySelector('[data-transfer]')?.addEventListener('click',async()=>{if(await confirm({title:t('Передать владение?','Transfer ownership?'),message:t('Вы останетесь администратором. Новый владелец сможет изменить вашу роль.','You will remain an administrator. The new owner can change your role.'),confirmLabel:t('Передать','Transfer')}))await run('transfer',{userId:member.ID});});
  }
  await render();
 }
 function familyIcon(c){const d=dialog(t('Пиктограмма семейного чата','Family chat icon')),host=d.querySelector('[data-content]');host.innerHTML=`<form><label>${t('Пиктограмма','Icon')}<select name="icon">${iconOptions(c.icon||'')}</select></label><button>${t('Сохранить','Save')}</button></form>`;let busy=false;host.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;try{await request(`/conversations/${encodeURIComponent(c.id)}/icon`,{method:'PUT',body:JSON.stringify({icon:e.currentTarget.elements.icon.value})});await refresh();d.close();}catch(e){d.querySelector('.error').textContent=e.message;}finally{busy=false;}};}
 async function recovery(){const d=dialog(t('Восстановление владельца группы','Recover group ownership')),host=d.querySelector('[data-content]');try{const list=await request('/application/ownerless-groups');host.innerHTML=list.map(g=>`<form data-group="${safe(g.id)}"><h3>${safe(g.title)}</h3><select name="userId" aria-label="${t('Новый владелец','New owner')}">${g.members.map(m=>`<option value="${safe(m.id)}">${safe(m.name)}</option>`).join('')}</select><button ${g.members.length?'':'disabled'}>${t('Назначить владельца','Assign owner')}</button>${g.members.length?'':`<p>${t('Нет активных участников. Требуется отдельное восстановление данных.','No active members. Separate data recovery is required.')}</p>`}</form>`).join('')||`<p>${t('Все группы имеют владельца.','All groups have an owner.')}</p>`;host.querySelectorAll('form').forEach(f=>{let busy=false;f.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;try{if(!await confirm({title:t('Назначить владельца?','Assign owner?'),message:f.querySelector('h3').textContent,confirmLabel:t('Назначить','Assign')}))return;await request(`/groups/${encodeURIComponent(f.dataset.group)}/recover`,{method:'POST',body:JSON.stringify({userId:f.elements.userId.value})});f.remove();await refresh();}catch(e){d.querySelector('.error').textContent=e.message;}finally{busy=false;}}});}catch(e){d.querySelector('.error').textContent=e.message;}}
 return {open,familyIcon,recovery};
}
