import {safe as safeText} from './api.js';
import {groupIcons} from './groups.js';
const safe=value=>safeText(value).replaceAll('"','&quot;').replaceAll("'",'&#39;');

export function initInterfamily({request,family,locale,refresh,confirm}){
 const t=(ru,en)=>locale()==='en'?en:ru;
 const warning=()=>t('Выбранные участники получат доступ ко всей истории чата. Администратор не включается автоматически.','Selected representatives can read the entire history. Administrators are not included automatically.');
 function dialog(title){const d=document.createElement('dialog');d.className='groupSettingsDialog';d.setAttribute('data-no-i18n','');d.innerHTML=`<header><h2>${safe(title)}</h2><button type="button" data-close>${t('Закрыть','Close')}</button></header><div data-content></div><p class="error" role="alert"></p>`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove(),{once:true});d.showModal();return d}
 const icons=value=>groupIcons.map(i=>`<option value="${safe(i)}" ${i===value?'selected':''}>${i||t('По умолчанию','Default')}</option>`).join('');
 function members(users,selected=[]){return `<fieldset><legend>${t('Представители вашей семьи','Your family representatives')}</legend><div class="interfamilyCandidates">${users.map(u=>`<label class="groupInviteToggle"><input type="checkbox" name="member" value="${safe(u.ID)}" ${selected.includes(u.ID)?'checked':''}>${safe(u.Name)}</label>`).join('')}</div></fieldset><p class="muted">${warning()}</p>`}
 const selected=form=>[...form.querySelectorAll('[name=member]:checked')].map(i=>i.value);
 function showCode(token){if(!token)return;const d=dialog(t('Код подключения семьи','Family connection code'));d.querySelector('[data-content]').innerHTML=`<p>${t('Передайте этот одноразовый код администратору другой семьи. Срок — 7 дней. После его запроса потребуется ваше подтверждение.','Share this single-use code with the other family administrator. It expires in 7 days. You must confirm their request.')}</p><input readonly aria-label="${t('Код','Code')}" value="${safe(token)}"><p>${t('Код не сохраняется в браузере. При потере можно выпустить новый.','The browser does not retain this code. You can generate a replacement.')}</p>`;d.querySelector('input').onclick=e=>e.target.select()}
 async function open(){
  const f=family();if(!f||!['owner','admin'].includes(f.role))return;
  const d=dialog(`${t('Семейные чаты','Family chats')} · ${f.title}`),host=d.querySelector('[data-content]'),error=d.querySelector('.error');let users=[],busy=false;
  async function load(){try{const [chats,candidates]=await Promise.all([request(`/interfamily?familyId=${encodeURIComponent(f.id)}`),request(`/interfamily?familyId=${encodeURIComponent(f.id)}&candidates=1`)]);if(!d.isConnected)return;users=candidates;host.innerHTML=`<div class="actions"><button type="button" data-create>${t('Создать чат','Create chat')}</button><button type="button" data-join>${t('Подключиться по коду','Connect using code')}</button></div><p class="muted">${t('Каждая семья управляет только своими представителями. Переписка доступна после подтверждения обеих сторон.','Each family manages only its representatives. Messaging requires approval from both sides.')}</p><ul class="groupMemberList">${chats.map(c=>`<li><span>${safe(c.icon||'👪')} ${safe(c.title)}<small>${safe(c.originTitle)}${c.targetTitle?' ↔ '+safe(c.targetTitle):''} · ${safe(({pending:t('Ожидает подключения','Awaiting connection'),requested:t('Ожидает подтверждения','Awaiting approval'),active:t('Активен','Active')})[c.state])}</small></span><button type="button" data-edit="${safe(c.id)}">${t('Настроить','Manage')}</button></li>`).join('')}</ul>`;host.querySelector('[data-create]').onclick=()=>create(false);host.querySelector('[data-join]').onclick=()=>create(true);host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(chats.find(c=>c.id===b.dataset.edit)))}catch(e){error.textContent=e.message;host.innerHTML=`<button type="button" data-retry>${t('Повторить','Retry')}</button>`;host.querySelector('button').onclick=load}}
  async function send(ed,path,body){if(busy)return null;busy=true;ed.querySelector('.error').textContent='';try{const out=await request(path,{method:'POST',body:JSON.stringify({...body,familyId:f.id})});await refresh();await load();return out}catch(e){ed.querySelector('.error').textContent=e.message;return null}finally{busy=false}}
  function create(join){const ed=dialog(join?t('Подключить семью','Connect family'):t('Новый семейный чат','New family chat')),key=crypto.randomUUID();ed.querySelector('[data-content]').innerHTML=`<form>${join?`<label>${t('Одноразовый код','Single-use code')}<input name="token" required autocomplete="off" maxlength="48"></label>`:`<label>${t('Название','Title')}<input name="title" required maxlength="120"></label><label>${t('Пиктограмма','Icon')}<select name="icon">${icons('')}</select></label>`}${members(users)}<button>${join?t('Отправить запрос','Send request'):t('Создать','Create')}</button></form>`;const form=ed.querySelector('form');form.onsubmit=async e=>{e.preventDefault();const ids=selected(form);if(!ids.length){ed.querySelector('.error').textContent=t('Выберите хотя бы одного участника.','Choose at least one representative.');return}const body={members:ids,requestKey:key,...(join?{token:form.elements.token.value.trim()}:{title:form.elements.title.value.trim(),icon:form.elements.icon.value})};const out=await send(ed,join?'/interfamily/invitation/join':'/interfamily',body);if(out){ed.close();showCode(out.token)}}}
  function edit(c){const ed=dialog(c.title),h=ed.querySelector('[data-content]');h.innerHTML=`<p>${safe(c.originTitle)}${c.targetTitle?' ↔ '+safe(c.targetTitle):''}</p>${c.state==='requested'&&c.originId===f.id?`<p>${t('Подтвердите подключение указанной семьи. Только после этого откроется общая история.','Confirm the named family. Only then will shared history become accessible.')}</p><button type="button" data-approve>${t('Подтвердить семью','Approve family')}</button>`:''}<form data-members>${members(users,c.members)}<button>${t('Сохранить состав','Save representatives')}</button></form><details><summary>${t('Название и пиктограмма','Title and icon')}</summary><form data-settings><label>${t('Название','Title')}<input name="title" required maxlength="120" value="${safe(c.title)}"></label><label>${t('Пиктограмма','Icon')}<select name="icon">${icons(c.icon)}</select></label><button>${t('Сохранить','Save')}</button></form></details><div class="actions">${c.state==='pending'&&c.originId===f.id?`<button type="button" data-renew>${t('Новый код','New code')}</button>`:''}<button type="button" class="dangerText" data-end>${t('Закрыть чат для обеих семей','Close chat for both families')}</button></div>`;
   const action=async(name,body={})=>{const out=await send(ed,`/interfamily/${encodeURIComponent(c.id)}/${name}`,{...body,version:c.version});if(out){ed.close();showCode(out.token)}};
   h.querySelector('[data-members]').onsubmit=async e=>{e.preventDefault();if(await confirm({title:t('Изменить состав?','Change representatives?'),message:warning(),confirmLabel:t('Сохранить','Save')}))await action('members',{members:selected(e.target)})};
   h.querySelector('[data-settings]').onsubmit=e=>{e.preventDefault();action('settings',{title:e.target.elements.title.value,icon:e.target.elements.icon.value})};
   h.querySelector('[data-approve]')?.addEventListener('click',async()=>{if(await confirm({title:t('Подтвердить подключение?','Approve connection?'),message:c.targetTitle+' — '+warning(),confirmLabel:t('Подтвердить','Approve')}))await action('approve')});
   h.querySelector('[data-renew]')?.addEventListener('click',()=>action('renew'));
   h.querySelector('[data-end]').onclick=async()=>{if(await confirm({title:t('Закрыть общий чат?','Close shared chat?'),message:t('Обе семьи потеряют доступ. История останется в базе, автоматического восстановления нет.','Both families lose access. History remains stored; there is no automatic reopening.'),confirmLabel:t('Закрыть чат','Close chat'),destructive:true}))await action('close')};
  }
  const reload=document.createElement('button');reload.type='button';reload.textContent=t('Обновить список','Refresh list');reload.onclick=load;d.querySelector('header').insertBefore(reload,d.querySelector('[data-close]'));
  await load();
 }
 return {open};
}
