import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
let JSDOM; try { ({ JSDOM }=require(process.env.TEST_JSDOM_PATH || 'jsdom')); } catch {}

test('Android shares require explicit confirmation and preserve the chat DOM', {skip:!JSDOM}, async()=>{
 const dom=new JSDOM('<aside><label class="sidebarSearch"></label></aside><dialog id="userMenuDialog"><button id="myProfile">Profile</button></dialog><article id="message">Existing message</article><textarea id="draft">Unsent draft</textarea>',{url:'https://chatfamily.site/',pretendToBeVisual:true});
 globalThis.document=dom.window.document;
 dom.window.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
 dom.window.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};
 globalThis.Option=dom.window.Option;
 let jobs=[{id:'12345678-1234-1234-1234-123456789abc',state:'draft',body:'Shared link',files:[{name:'<unsafe>.txt',bytes:12}]}];
 const submissions=[];
 let openId='',modern=true;
 const plugin={list:async()=>{const result={jobs,...(modern?{shareOpenRequests:true,openId}:{})};openId='';return result;},submit:async data=>{submissions.push(data);jobs=[{...jobs[0],...data,state:'queued'}];},discard:async()=>{jobs=[];}};
 globalThis.Capacitor={isNativePlatform:()=>true,registerPlugin:()=>plugin};
 const original=globalThis.setInterval; let tick; globalThis.setInterval=fn=>{tick=fn;return 1;};
 try {
  const {initIncomingShares}=await import('./mobile/incoming-share.js');
  const message=document.querySelector('#message'), draft=document.querySelector('#draft');
  const request=async path=>path==='/conversations'?[{id:'c1',title:'Family',kind:'family',familyId:'f1'}]:path==='/families'?[{id:'f1',title:'Family space'}]:[];
  const sent=[];
  initIncomingShares({user:{ID:'u1',Name:'Me'},locale:()=> 'en',request,onSent:(cid,navigate)=>sent.push({cid,navigate})});
  await new Promise(r=>setTimeout(r,0));
  assert.equal(submissions.length,0,'Receiving files must not send');
  assert.equal(document.querySelector('dialog[open]'),null,'ordinary entry with old draft must stay in chat');
  await tick();assert.equal(document.querySelector('dialog[open]'),null,'polling old draft must stay quiet');
  openId=jobs[0].id;await tick();await new Promise(r=>setTimeout(r,0));
  assert.ok(document.querySelector('dialog[open]'),'new Android share opens once');
  document.querySelector('.shareClose').click();await tick();assert.equal(document.querySelector('dialog[open]'),null,'dismissed share must not reopen');
  document.querySelector('.mobileInboxButton').click();await new Promise(r=>setTimeout(r,0));
  assert.ok(document.querySelector('.shareQueue').textContent.includes('<unsafe>.txt'));
  assert.equal(document.querySelector('unsafe'),null);
  document.querySelector('[data-action="choose"]').click();
  await new Promise(r=>setTimeout(r,0));
  document.querySelector('[data-recipient="chat:c1"]').click();
  const caption=document.querySelector('.shareCaption'); caption.value='My caption'; caption.focus();
  await tick();
  assert.equal(document.querySelector('.shareCaption'),caption);
  assert.equal(caption.value,'My caption');
  assert.equal(document.activeElement,caption);
  document.querySelector('.shareForm').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));
  await new Promise(r=>setTimeout(r,0));
  assert.equal(submissions.length,1); assert.equal(submissions[0].conversationId,'c1'); assert.equal(submissions[0].userId,'u1');
  assert.equal(document.querySelector('.mobileShareDialog').open,false,'recipient dialog closes after queue acceptance');
  await tick();assert.equal(document.querySelector('.mobileShareDialog').open,false,'polling must not reopen queued share');
  assert.equal(sent.length,0,'queue acceptance is not successful delivery');
  jobs=[{...jobs[0],state:'sent'}];await tick();
  assert.deepEqual(sent,[{cid:'c1',navigate:true}],'successful share opens recipient chat');
  await tick();assert.equal(sent.length,1,'polling does not repeat navigation');
  jobs=[{id:'history',userId:'u1',conversationId:'old',state:'sent',files:[]}];await tick();
  assert.equal(sent.length,1,'saved history must not navigate or refresh chats');
  assert.equal(document.querySelector('.shareHistoryLink, .shareHistoryDialog'),null,'sent history has no UI');
  assert.equal(document.querySelector('.shareQueue .shareJob'),null,'successful shares leave the queue');
  assert.equal(document.querySelector('.mobileInboxButton').textContent,'Incoming attachments');
  jobs=[{id:'retry',userId:'u1',conversationId:'c1',state:'failed',body:'Retry caption',files:[]}];await tick();
  assert.ok(document.querySelector('[data-action="discard"]'),'failed share can be cancelled');
  document.querySelector('[data-action="retry"]').click();await new Promise(r=>setTimeout(r,0));
  assert.equal(submissions.at(-1).id,'retry','retry keeps the idempotency key');
  assert.equal(submissions.at(-1).conversationId,'c1');
  jobs=[{...jobs[0],state:'sent'}];await tick();
  assert.deepEqual(sent.at(-1),{cid:'c1',navigate:true});
  assert.equal(document.querySelector('#message'),message); assert.equal(document.querySelector('#draft'),draft); assert.equal(draft.value,'Unsent draft');
  jobs=[{id:'other',userId:'another',state:'failed',body:'Private',files:[]}]; await tick();
  assert.equal(document.querySelector('.shareQueue').textContent.includes('Private'),false);
  modern=false;jobs=[{id:'legacy-new',state:'draft',body:'New legacy share',files:[]}];await tick();
  assert.ok(document.querySelector('.mobileShareDialog').open,'legacy APK detects a new share after initial snapshot');
 } finally { globalThis.setInterval=original; delete globalThis.Capacitor; dom.window.close(); }
});
